# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3d6dc2cd1a5cf15eb82ab5e068ee6bb4a5cbda3aa2cbf680ca45c79340d642401060f2ff89c3a9dc1125a777005f51f9a75d6f70129da334368f2aa0cdca03

test:
  secret_key_base: 0a5091c653d2a9862f8870c1c423a8fdfcd89c8125c40247a0de57872432fb5cc25727652a1298ed1b977d0e1099bf1c6b2a0ce2a91ed723f94b8b5d755ba59e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
